# Generated by Django 2.1 on 2018-08-14 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_nombre', models.CharField(max_length=200)),
                ('e_categoria', models.CharField(choices=[('C', 'Conferencia'), ('S', 'Seminario'), ('Co', 'Congreso'), ('Cu', 'Curso')], max_length=1)),
                ('e_lugar', models.CharField(max_length=200)),
                ('e_direccion', models.CharField(max_length=200)),
                ('e_fechaIni', models.DateTimeField(default=datetime.date.today)),
                ('e_fechaFin', models.DateTimeField()),
                ('e_tipo', models.CharField(choices=[('V', 'Virtual'), ('P', 'Presencial')], max_length=1)),
            ],
        ),
    ]
